### PR TITLE
NGINX agent cannot find the default network interface on Linux hosts.…

### PR DESCRIPTION
**Pull request by richbrowne**
… (#317)

The parser was skipping over the first (header) line with the first invocation of scanner.Scan().  The second invocation of scanner.Scan() called in the for loop points to the first line of route data; however, this line was being skipped.  The tests were incorrect because they started with a newline before the header.

### Proposed changes
Remove the logic to skip over the first line of route data for Linux hosts and corrected the unit tests.

Tested the change on Ubuntu 20.04.5 LTS

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [`CONTRIBUTING`](https://github.com/nginx/agent/blob/main/docs/CONTRIBUTING.md) document
- [x] I have run ```make install-tools``` and have attached any dependency changes to this pull request
- [x] If applicable, I have added tests that prove my fix is effective or that my feature works
- [x] If applicable, I have checked that any relevant tests pass after adding my changes
- [x] If applicable, I have updated any relevant documentation ([`README.md`](https://github.com/nginx/agent/blob/main/README.md))
- [ ] If applicable, I have tested my cross-platform changes on Ubuntu 22, Redhat 8, SUSE 15 and FreeBSD 13

### CODE REVIEW

**Comment by richbrowne** [comment]
@nkashiv @achawla2012 Could you review too and get this pushed through?

**Comment by achawla2012** [comment]
> @nkashiv @achawla2012 Could you review too and get this pushed through?

The default interface is the one that has 0 for both destination and mask.  Therefore we will also have to check if mask is 0 as well. https://github.com/jackpal/gateway/blob/master/gateway_parsers.go#L69

**Comment by achawla2012** [comment]
LGTM

**Comment by Dean-Coakley** [comment]
Fixed in https://github.com/nginx/agent/pull/331

**Pull request closed without merging**
